version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      # Automatically generate a random root password on startup
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      # These values are used during the install, as described in the `README`
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticket_pwd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      - PMA_HOST=mysql
      - PMA_USER=osticket
      - PMA_PASSWORD=osticket_pwd
    ports:
      - "8000:80"
  apache:
    # Use a custom image, which has the required extensions
    build: ./docker/php/
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/ost-config.php:/var/www/html/include/ost-config.php
